# Website settings
title: Home
description: Akshay Siwal Resume.
keywords: Akshay,Akshay Siwal,blog,SRE,devops,adobe
baseurl:  / # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: http://www.akshaysiwal.com  # url should be 'http://<github_username>.github.io/homepage' as before
img_path: /static/assets/img/blog  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: Akshay Siwal  # Be used at blog posts' author.
  first_name: Akshay  # Be used at index page about me section.
  last_name: Siwal  # Be used at index page about me section.
  avatar: /static/assets/img/landing/avatar.png  # upload your avatar at directory and edit it.
  github_username: AkshaySiwal  # Leave blank if you don't have now
  linkedin_id: akshay-siwal-4b08b916 # Leave blank if you don't have now
  facebook_username: akshay.siwal.5  # Leave blank if you don't have now
  #twitter_username: akshaysiwal  # Leave blank if you don't have now
  email: akshay231990@gmail.com  # Leave blank if you don't have now
  cv: /static/assets/resume/Akshay-Resume.pdf  # An online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: icon-apache
    - name: fa-linux
    - name: icon-centos   
    - name: icon-redhat  
    - name: icon-mysql
    - name: icon-mongodb
    
  skill_icon2:
    - name: icon-python
    - name: icon-aws
    - name: icon-azure
    - name: icon-hadoop
    - name: icon-script
    
   
 
  desc: Hi. Introduce myself will be here.  # Describe yourself.

# comment
disqus:  # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
  name: akshaysiwal

# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  # id:

## google optimize
go:
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: on  # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: on  # index page carousel switch
blog_carousel: on  # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

